name: docker_push
description: push image to docker_hub
runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          docker build . --file ${{inputs.path_dockerfile}} --tag $(date +%s)
        else
          docker build . --file ${{inputs.path_dockerfile}} --tag ${{ inputs.tag_name }}:$(date +%s)
        fi
        echo "DOCKER_IMAGE_NAME=${{inputs.image_name}}" >> $GITHUB_ENV
      shell: bash