name: docker_action
description: multiple actions
runs:
  using: composite
  steps:
    - run: |
        docker build . --file Dockerfile --tag exfinalcicd:$(date +%s)
        docker image ls
      shell: bash