name: docker_action
description: multiple actions
inputs:
  path_dockerfile:
    description: Path of the dockerfile
    required: false
    default: "Dockerfile"
  image_name:
    description: Name of the image
    required: true
    default: "default"
  tag_name:
    description: Name of the tag
    required: false
    default: "default"

runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          docker build . --file ${{inputs.path_dockerfile}} --tag $(date +%s)
        else
          docker build . --file ${{inputs.path_dockerfile}} --tag ${{ inputs.image_name }}:${{ inputs.tag_name }}
        fi
        echo "DOCKER_IMAGE_NAME=:${{ inputs.image_name }}:${{ inputs.tag_name }}" >> $GITHUB_ENV
        docker image tag ${{env.DOCKER_IMAGE_NAME}} paulomano147/${{env.DOCKER_IMAGE_NAME}}
      shell: bash