name: docker_action
description: multiple actions
inputs:
  path_dockerfile:
    description: Path of the dockerfile
    required: false
    default: "Dockerfile"
  image_name:
    description: Name of the image
    required: true
    default: "default"
  tag_name:
    description: Name of the tag
    required: false
    default: "default"

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image
      run: docker push paulomano147/day3:tagname