name: docker_push
description: push image to docker_hub
inputs:
  docker_image:
    description: Name of the image
    required: true
    default: "default"

runs:
  using: composite
  steps:

    - name: Push image
      run: docker push paulomano147/${{inputs.docker_image}}
      shell: bash