name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: PaulBroo/academy/.github/actions/docker_build@main
      with:
        path_dockerfile: Dockerfile
        image_name: ubuntu
        tag_name: tag
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: PaulBroo/academy/.github/actions/docker_push@main
      with:
        docker_image: ${{env.DOCKER_IMAGE_NAME}}

